### ISSUE TITLE
Missing test dataset

### ISSUE THREAD

**Issue by charlotte823149** [google-research/human-scene-transformer#15]
Hello,
I am trying to test your model. However, when I downloading the test dataset, it automatically start downloading the file with training dataset. Should I go to JRDB website to request their dataset? And what dataset should I request?

Also, when I trying to run "python train.py", it is missing "dataset_spec.pb" file. And I could not find it anywhere within all the link you provided.

Thanks you

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out!

> However, when I downloading the test dataset, it automatically start downloading the file with training dataset

Apologies! This was a bug in the README, which we just fixed. The link should now point to the correct file.

> Also, when I trying to run "python train.py", it is missing "dataset_spec.pb" file.

Could you please provide the entire error message?

Thanks
Tim

**Comment by charlotte823149** [comment]
Thanks for updating the test dataset, but the dataset itself is missing "labels" folder. So when we are running the jrdb_preprocess_test.py it can not correctly generate the dataset.

The error message we got from train.py is the following:

WARNING:tensorflow:From /home/cam/human-scene-transformer/human_scene_transformer/jrdb/input_fn.py:555: load (from tensorflow.python.data.experimental.ops.io) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.load(...)` instead.
W1103 14:49:08.859732 140565449860928 deprecation.py:364] From /home/cam/human-scene-transformer/human_scene_transformer/jrdb/input_fn.py:555: load (from tensorflow.python.data.experimental.ops.io) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.load(...)` instead.
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    app.run(main)
  File "/home/cam/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/cam/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 102, in main
    ds_train = jrdb_input_fn.get_train_dataset(dataset_params)
  File "/home/cam/human-scene-transformer/human_scene_transformer/jrdb/input_fn.py", line 709, in get_train_dataset
    ds_train = load_dataset(
  File "/home/cam/human-scene-transformer/human_scene_transformer/jrdb/input_fn.py", line 614, in load_dataset
    scene_dataset = _load_scene_with_features(
  File "/home/cam/human-scene-transformer/human_scene_transformer/jrdb/input_fn.py", line 555, in _load_scene_with_features
    raw_dataset = tf.data.experimental.load(
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 371, in new_func
    return func(*args, **kwargs)
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/io.py", line 166, in load
    return dataset_ops.Dataset.load(path, element_spec, compression, reader_func)
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1811, in load
    return load_op._load(
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/load_op.py", line 28, in _load
    return _LoadDataset(path, element_spec, compression, reader_func)
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/load_op.py", line 46, in __init__
    encoded_spec = f.read()
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/home/cam/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: <dataset_path>/bytes-cafe-2019-02-07_0/agents/position/dataset_spec.pb; No such file or directory

I'm guessing it may be raised because we're not having the correct training dataset?
Lastly, can you provide a pretrained model or a simple testing model to let us have a basic idea of knowing what's the format of output?

**Comment by Tim-Salzmann** [comment]
Hi,

If the pre-processing and creation of the dataset does not succeed, the training procedure is expected to fail. Could you please post the error message you are getting during dataset generation?

> Thanks for updating the test dataset, but the dataset itself is missing "labels" folder.

Is this for the JRDB train or test dataset? For the train dataset, the labels are expected to be part of the download. For the test dataset you will have to separately download the labels as described here [1].

> Lastly, can you provide a pretrained model or a simple testing model to let us have a basic idea of knowing what's the format of output?

You can download the pre-trained checkpoints here [2].

Let me know if you have any other questions.

Best
Tim

[1] https://github.com/google-research/human-scene-transformer/tree/main/human_scene_transformer/data#get-the-leaderboard-test-set-tracks
[2] https://storage.googleapis.com/gresearch/human_scene_transformer/checkpoints.zip

**Comment by Tim-Salzmann** [comment]
Hi Charlotte,

just checking in to see if this solved your problem?

Let me know if you have any other questions. Otherwise, feel free to close this issue.

Best
Tim

**Comment by charlotte823149** [comment]
Thank you for the response, we still getting some problems but its all about our dependencies. I think we're all good here. Thanks again
